set(_CATKIN_CURRENT_PACKAGE "xyi2_brain")
set(xyi2_brain_VERSION "0.0.0")
set(xyi2_brain_MAINTAINER "cyb7369299 <cyb7369299@todo.todo>")
set(xyi2_brain_PACKAGE_FORMAT "1")
set(xyi2_brain_BUILD_DEPENDS "cv_bridge" "image_transport" "interactive_markers" "pcl_conversions" "pcl_ros" "roscpp" "rospy" "sensor_msgs" "std_msgs" "tf")
set(xyi2_brain_BUILD_EXPORT_DEPENDS "cv_bridge" "image_transport" "interactive_markers" "pcl_conversions" "pcl_ros" "roscpp" "rospy" "sensor_msgs" "std_msgs" "tf")
set(xyi2_brain_BUILDTOOL_DEPENDS "catkin")
set(xyi2_brain_BUILDTOOL_EXPORT_DEPENDS )
set(xyi2_brain_EXEC_DEPENDS "cv_bridge" "image_transport" "interactive_markers" "pcl_conversions" "pcl_ros" "roscpp" "rospy" "sensor_msgs" "std_msgs" "tf")
set(xyi2_brain_RUN_DEPENDS "cv_bridge" "image_transport" "interactive_markers" "pcl_conversions" "pcl_ros" "roscpp" "rospy" "sensor_msgs" "std_msgs" "tf")
set(xyi2_brain_TEST_DEPENDS )
set(xyi2_brain_DOC_DEPENDS )
set(xyi2_brain_DEPRECATED "")